"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { AppShell } from "../../components/app-nav";
import { cleanText, formatDate, statusClass } from "../../components/format";
import { MarkdownReport } from "../../components/markdown-report";
import { getAuthHeaders, getSignedInUser } from "../../lib/supabase-browser";

type ReportState = {
  report: { id: string; title?: string | null; markdown?: string | null; created_at?: string | null; summary_json?: Record<string, any> | null };
  run: { id: string; status: string; mode?: string | null; final_summary?: string | null } | null;
  toolCalls: Array<Record<string, any>>;
  evidence: Array<Record<string, any>>;
  scores: Array<Record<string, any>>;
};

export default function ReportPage() {
  const { id } = useParams<{ id: string }>();
  const router = useRouter();
  const [email, setEmail] = useState<string | null>(null);
  const [state, setState] = useState<ReportState | null>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    async function load() {
      const user = await getSignedInUser();
      if (!user) {
        router.replace("/login");
        return;
      }
      setEmail(user.email ?? null);
      const response = await fetch(`/api/reports/${id}`, {
        headers: await getAuthHeaders(),
        cache: "no-store",
      });
      const body = await response.json().catch(() => ({}));
      if (!response.ok) {
        throw new Error(body.error ?? "Could not load report.");
      }
      setState(body);
    }
    load().catch((loadError) => setError(loadError instanceof Error ? loadError.message : String(loadError)));
  }, [id, router]);

  const failedCalls = state?.toolCalls?.filter((call) => call.status === "failed") ?? [];
  const successfulCalls = state?.toolCalls?.filter((call) => call.status === "success") ?? [];
  const headings = extractReportHeadings(state?.report?.markdown);
  const draftArtifacts = extractDraftArtifacts(state?.toolCalls ?? []);
  const evidenceTypes = summarizeEvidenceTypes(state?.evidence ?? []);
  const generatedBy = state?.report?.summary_json?.generated_by ?? "Augur Analyst";
  const topScores = [...(state?.scores ?? [])].sort((a, b) => Number(b.confidence ?? 0) - Number(a.confidence ?? 0));

  return (
    <AppShell userEmail={email}>
      <header className="topbar commandTopbar">
        <div>
          <p className="eyebrow">Source-backed report</p>
          <h2>{state?.report?.title ?? "Report"}</h2>
          <p>{state?.report?.created_at ? formatDate(state.report.created_at) : "Loading readable report."}</p>
        </div>
        <div className="topbarActions">
          <Link className="secondaryLink" href="/dashboard">
            Overview
          </Link>
          {state?.run ? (
            <Link className="actionLink" href={`/runs/${state.run.id}`}>
              View run trace
            </Link>
          ) : null}
        </div>
      </header>

      {error ? <div className="errorBanner">{error}</div> : null}
      {!state ? <div className="skeletonRow" /> : null}

      {state ? (
        <>
          <section className="reportMetaStrip">
            <div>
              <span>Run mode</span>
              <strong>{state.run?.mode ?? "report"}</strong>
            </div>
            <div>
              <span>Generated by</span>
              <strong>{cleanText(generatedBy, 120)}</strong>
            </div>
            <div>
              <span>Successful tools</span>
              <strong>{successfulCalls.length}</strong>
            </div>
            <div>
              <span>Evidence rows</span>
              <strong>{state.evidence.length}</strong>
            </div>
          </section>

          {topScores.length ? (
            <section className="memoScoreStrip">
              {topScores.map((score) => (
                <div key={score.id ?? score.city}>
                  <span>{score.city}</span>
                  <strong>{score.confidence}%</strong>
                  <p>
                    M {score.development_momentum} · Z {score.zoning_friction} · C {score.code_occupancy_risk} · P {score.policy_risk}
                  </p>
                </div>
              ))}
            </section>
          ) : null}

          <section className="reportLayout">
            <div className="reportPanel readable">
              <MarkdownReport markdown={state.report.markdown} />
            </div>
            <aside className="evidencePanel reportAside">
              <div className="sectionHeader">
                <div>
                  <h3>Memo Outline</h3>
                  <p className="sectionSubcopy">Sticky section map for the full intelligence memo.</p>
                </div>
                <span>{headings.length}</span>
              </div>
              <nav className="reportOutline" aria-label="Report sections">
                {headings.slice(0, 18).map((heading) => (
                  <a href={`#${heading.id}`} key={heading.id}>
                    {heading.title}
                  </a>
                ))}
                {!headings.length ? <p className="mutedText">No markdown section headings were found.</p> : null}
              </nav>

              <div className="sectionHeader">
                <div>
                  <h3>Source Status</h3>
                  <p className="sectionSubcopy">Failures stay visible and reduce confidence.</p>
                </div>
                <span className={failedCalls.length ? "fail" : "pass"}>{failedCalls.length ? "gaps" : "complete"}</span>
              </div>
              {failedCalls.length ? (
                <div className="failureList">
                  {failedCalls.map((call) => (
                    <div key={call.id}>
                      <strong>{call.tool_name}</strong>
                      <p>{cleanText(call.error_message ?? call.output_summary, 260)}</p>
                      <small className={`checkBadge ${statusClass(call.status)}`}>confidence reduced</small>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="mutedText">No failed tool calls were recorded for this report run.</p>
              )}

              <div className="sectionHeader">
                <div>
                  <h3>Reviewed Drafts</h3>
                  <p className="sectionSubcopy">Separated from memo evidence so they do not look executed.</p>
                </div>
                <span>{draftArtifacts.length}</span>
              </div>
              <div className="artifactList">
                {draftArtifacts.map((artifact) => (
                  <div key={artifact.name}>
                    <strong>{artifact.label}</strong>
                    <p>{cleanText(artifact.summary, 300)}</p>
                    <small>Review required. No external action was executed.</small>
                  </div>
                ))}
                {!draftArtifacts.length ? <p className="mutedText">No draft artifacts were created for this report run.</p> : null}
              </div>

              <div className="sectionHeader">
                <div>
                  <h3>Evidence Mix</h3>
                  <p className="sectionSubcopy">Public records, official pages, and cached source rows.</p>
                </div>
                <span>{evidenceTypes.length}</span>
              </div>
              <div className="sourceMix">
                {evidenceTypes.map((item) => (
                  <div key={item.type}>
                    <span>{item.type}</span>
                    <strong>{item.count}</strong>
                  </div>
                ))}
              </div>

              <div className="sectionHeader">
                <div>
                  <h3>Evidence</h3>
                  <p className="sectionSubcopy">First ten evidence rows linked from the report packet.</p>
                </div>
                <span>{state.evidence.length}</span>
              </div>
              <div className="evidenceList">
                {state.evidence.slice(0, 10).map((item) => (
                  <a href={item.source_url ?? "#"} key={item.id} rel="noreferrer" target="_blank">
                    <strong>{cleanText(item.title ?? item.source_name ?? "Evidence item", 160)}</strong>
                    <p>{cleanText(item.excerpt ?? item.summary ?? item.metadata_json?.summary, 300)}</p>
                    <span>{cleanText(item.evidence_type ?? item.source_name ?? item.source_url ?? "public source", 120)}</span>
                  </a>
                ))}
              </div>
            </aside>
          </section>

          <section className="evidenceRegister">
            <div className="sectionHeader">
              <h3>Evidence Register</h3>
              <span>{state.evidence.length} rows</span>
            </div>
            <div className="evidenceTable">
              <div className="evidenceTableHead">
                <span>Evidence</span>
                <span>Type</span>
                <span>Source</span>
              </div>
              {state.evidence.map((item) => (
                <a href={item.source_url ?? "#"} key={item.id} rel="noreferrer" target="_blank">
                  <strong>{cleanText(item.title ?? item.source_name ?? "Evidence item", 180)}</strong>
                  <span>{cleanText(item.evidence_type ?? "public record", 90)}</span>
                  <span>{cleanText(item.source_name ?? item.source_url ?? "cached public record", 160)}</span>
                </a>
              ))}
            </div>
          </section>
        </>
      ) : null}
    </AppShell>
  );
}

function extractReportHeadings(markdown?: string | null) {
  return String(markdown ?? "")
    .split(/\r?\n/)
    .filter((line) => line.startsWith("## "))
    .map((line) => {
      const title = cleanText(line.replace(/^##\s+/, ""), 120);
      return {
        title,
        id: title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""),
      };
    })
    .filter((heading) => heading.id);
}

function summarizeEvidenceTypes(evidence: Array<Record<string, any>>) {
  const counts = new Map<string, number>();
  for (const item of evidence) {
    const type = cleanText(item.evidence_type ?? "evidence", 64);
    counts.set(type, (counts.get(type) ?? 0) + 1);
  }
  return [...counts.entries()]
    .map(([type, count]) => ({ type, count }))
    .sort((a, b) => b.count - a.count);
}

function extractDraftArtifacts(toolCalls: Array<Record<string, any>>) {
  const labels: Record<string, string> = {
    find_public_contact_paths: "Contact Paths",
    draft_outreach_email: "Draft Outreach Email",
    draft_talking_points: "Draft Talking Points",
    draft_social_campaign: "Public Messaging Concepts",
    suggest_visual_assets: "Visual Asset Suggestions",
  };

  return toolCalls
    .filter((call) => labels[call.tool_name] && call.status === "success")
    .map((call) => ({
      name: call.tool_name,
      label: labels[call.tool_name],
      summary: call.output_summary ?? call.output_json?.summary ?? "Created reviewed artifact.",
    }));
}
